@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_user
POST {{baseUrl}}/user
Content-Type: application/json

{
	"name": "John Doe",
	"email": "johndoe@example.com",
	"password": "123456",
	"cpf": "07634444138",
	"phone": "71912345678",
	"DistrictCouncil": "Prefeitura-Bairro Cidade Baixa"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "123456"
}

###

# @name create_resquests
POST {{baseUrl}}/resquests
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}